#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pigz
Version  : 2.3.3
Release  : 23
URL      : http://zlib.net/pigz/pigz-2.3.3.tar.gz
Source0  : http://zlib.net/pigz/pigz-2.3.3.tar.gz
Summary  : pigz is a parallel implementation of gzip which utilizes multiple cores
Group    : Development/Tools
License  : Apache-2.0 Zlib
Requires: pigz-bin
BuildRequires : pkgconfig(zlib)
BuildRequires : zlib-dev
Patch1: build.patch
Patch2: rsync.patch
Patch3: link.patch
Patch4: error.patch

%description
pigz, which stands for parallel implementation of gzip, is a fully functional replacement for gzip that exploits multiple processors and multiple cores to the hilt when compressing data. pigz was written by Mark Adler, and uses the zlib and pthread libraries.

%package bin
Summary: bin components for the pigz package.
Group: Binaries

%description bin
bin components for the pigz package.


%prep
%setup -q -n pigz-2.3.3
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make tests CFLAGS="$RPM_OPT_FLAGS"

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gzip
/usr/bin/pigz
