#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pigz
Version  : 2.4
Release  : 34
URL      : http://zlib.net/pigz/pigz-2.4.tar.gz
Source0  : http://zlib.net/pigz/pigz-2.4.tar.gz
Summary  : pigz is a parallel implementation of gzip which utilizes multiple cores
Group    : Development/Tools
License  : Apache-2.0 Zlib
Requires: pigz-bin
Requires: pigz-doc
BuildRequires : pkgconfig(zlib)
BuildRequires : zlib-dev
Patch1: 0001-Add-make-install-for-pigz.patch
Patch2: rsync.patch
Patch3: link.patch
Patch4: error.patch

%description
pigz, which stands for parallel implementation of gzip, is a fully functional replacement for gzip that exploits multiple processors and multiple cores to the hilt when compressing data. pigz was written by Mark Adler, and uses the zlib and pthread libraries.

%package bin
Summary: bin components for the pigz package.
Group: Binaries

%description bin
bin components for the pigz package.


%package doc
Summary: doc components for the pigz package.
Group: Documentation

%description doc
doc components for the pigz package.


%prep
%setup -q -n pigz-2.4
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1514392544
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make tests CFLAGS="$RPM_OPT_FLAGS"

%install
export SOURCE_DATE_EPOCH=1514392544
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gzip
/usr/bin/pigz

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
